sudo: required
dist: trusty
language: node_js
node_js:
  - '7'
install:
  - npm install -g ganache-cli
  - npm install -g ethereumjs-testrpc
  - npm install
script:
  - npm test
before_script:
  - ganache-cli > /dev/null &
  - sleep 5
after_script:
  - npm run coverage && cat coverage/lcov.info | coveralls